## NumPy-创建ndarray数组之random模块

- random.random()
- random.rand()
- random.randint()
- random.randn()
- random.standard_normal()
- random.random_sample()
- random.bytes()
- random.choice()
- random.permutation()
- random.shuffle()
- random.seed()

In [1]:
import numpy as np

### random.random()

产生[0.0,1.0)之间的浮点数

In [9]:
np.random.random()

0.8364079493084979

In [11]:
np.random.random((4,3))

array([[0.7312988 , 0.26094802, 0.3113314 ],
       [0.31868361, 0.34299623, 0.60165061],
       [0.70323747, 0.66713048, 0.22984002],
       [0.14439304, 0.34856438, 0.10585813]])

### random.rand()
- np.random.rand(d0, d1, ..., dn)

生成一个[0, 1)上的(d0, d1, ..., dn)维随机浮点数组，若没有参数输入，则生成一个随机浮点数

In [2]:
np.random.rand()

0.9748783659378922

In [3]:
np.random.rand(4,3)

array([[0.6220083 , 0.60707842, 0.71092161],
       [0.49406077, 0.85060594, 0.51172854],
       [0.97663214, 0.3091979 , 0.68683116],
       [0.14639814, 0.77756249, 0.18472775]])

- random与rand的区别：

生成4×3的数组，0-1之间的均匀分布,random.rand(a,b)与而random.random((a,b))作用一样,但是rand后跟元素的格式，而random后跟元组的格式.

### random.randint()
- np.random.randint(low, high=None, size=None, dtype='I')

生成size个整数，取值区间为[low, high)，若没有输入参数high则取值区间为[0, low)

In [17]:
np.random.randint(4)

1

In [21]:
np.random.randint(10,size=1)

array([4])

In [22]:
np.random.randint(10,size=(3,4,5))

array([[[1, 4, 5, 7, 0],
        [0, 6, 6, 4, 8],
        [6, 6, 9, 6, 9],
        [2, 1, 1, 9, 6]],

       [[2, 4, 9, 1, 1],
        [2, 5, 4, 0, 7],
        [7, 5, 9, 1, 0],
        [6, 4, 6, 6, 3]],

       [[0, 8, 1, 0, 8],
        [2, 1, 7, 0, 6],
        [1, 3, 4, 1, 2],
        [4, 3, 6, 3, 0]]])

In [23]:
np.random.randint(2,8,size=(2,2,4),dtype=np.int64)

array([[[3, 7, 7, 5],
        [5, 6, 6, 4]],

       [[2, 2, 3, 4],
        [2, 2, 4, 5]]])

## random.randn()
- np.random.randn(d0, d1, ..., dn)
生成一个(d0, d1, ..., dn)维的浮点数组，若没有参数输入，则生成一个随机浮点数,取值范围：正态分布的随机样本

In [4]:
np.random.randn()

0.03493007843194171

In [5]:
np.random.randn(1)

array([0.73532882])

In [7]:
np.random.randn(5)

array([-1.07067781, -0.02491489, -0.30259131,  1.889912  , -0.29892613])

In [8]:
np.random.randn(2,3)

array([[-0.48756394,  1.65534792,  0.07543256],
       [-0.36508387,  0.43867554,  1.51762546]])

### random.standard_normal()

生成一个浮点数或N维浮点数组，随机样本服从标准正态分布

In [24]:
np.random.standard_normal()

-1.2476858849632433

In [25]:
np.random.standard_normal(4)

array([ 0.09739316, -1.35170254, -1.39557536,  0.41952356])

In [26]:
np.random.standard_normal((2,4))

array([[-1.37732613,  1.54126693,  0.44400375,  0.39408709],
       [-0.13414737, -0.42455666, -0.04567694,  0.59267845]])

- Numpy中的三个常用正态分布函数randn，standard_normal， normal的区别(https://www.cnblogs.com/luckyboy314/p/11715643.html)

### random.random_sample()

生成一个[0,1)之间随机浮点数或N维浮点数组

In [32]:
np.random.random_sample()

0.6067410285420141

In [33]:
np.random.random_sample(4)

array([0.99066741, 0.53922689, 0.20274329, 0.50076354])

In [35]:
np.random.random_sample((3,4,6))

array([[[0.98245355, 0.07753816, 0.41642765, 0.55547109, 0.03824864,
         0.69047854],
        [0.29560996, 0.77762241, 0.8350561 , 0.1227281 , 0.22989102,
         0.48291557],
        [0.81723872, 0.6908164 , 0.43692391, 0.5406839 , 0.99120647,
         0.32051579],
        [0.69212025, 0.50815855, 0.24652537, 0.59948607, 0.67616009,
         0.71002592]],

       [[0.11349312, 0.2499391 , 0.09190913, 0.23824638, 0.08404448,
         0.89858357],
        [0.77698758, 0.52631972, 0.62092627, 0.08179516, 0.81520227,
         0.38670091],
        [0.51455976, 0.12193649, 0.80644985, 0.1752869 , 0.69702607,
         0.91228503],
        [0.65065587, 0.98185661, 0.72124382, 0.36453947, 0.32268357,
         0.79398751]],

       [[0.89893246, 0.29504551, 0.20011478, 0.75134642, 0.10410593,
         0.49443564],
        [0.52068268, 0.07207955, 0.05686   , 0.11376154, 0.10892118,
         0.26927863],
        [0.44765475, 0.41952378, 0.69639913, 0.27828767, 0.84053531,
         0.518458

### random.bytes(length)

 生成随机字节


In [42]:
np.random.bytes(1)

b'\xc5'

In [41]:
np.random.bytes(6)

b'\x8a\x05\xe2*o~'

### random.choice()

- numpy.random.choice(a, size=None, replace=True, p=None)

 从a（数组）中选取size（维度）大小的随机数，replace=True表示可重复抽取，p是a中每个数出现的概率

 若a是整数，则a代表的数组是arange(a)

In [43]:
np.random.choice(5)

3

In [45]:
np.random.choice([0.2, 0.6])

0.2

In [47]:
np.random.choice([2,9],p=[1,0])

2

In [48]:
np.random.choice([2,9],p=[0.3,0.7])

9

In [49]:
np.random.choice(6,5)

array([3, 2, 4, 2, 3])

In [50]:
np.random.choice(6,5,False)

array([3, 1, 4, 2, 5])

In [51]:
np.random.choice(20,(2,2,3),False)

array([[[ 7, 10,  4],
        [15, 17,  1]],

       [[ 8,  3, 12],
        [ 0,  2,  6]]])

### random.permutation()

- random.permutation(x)

 随机打乱x中的元素。若x是整数，则打乱arange(x)，若x是一个数组，则将copy(x)的第一位索引打乱，意思是先复制x，对副本进行打乱处理，打乱只针对数组的第一维

In [52]:
np.random.permutation(6)

array([3, 0, 5, 2, 1, 4])

In [53]:
np.random.permutation(6)

array([0, 5, 1, 3, 4, 2])

In [54]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [55]:
np.random.permutation(arr1)

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np.random.permutation(arr1)

array([[4, 5, 6],
       [1, 2, 3]])

In [57]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

### random.shuffle()

- np.random.shuffle(x)
 与permutation类似，随机打乱x中的元素。若x是整数，则打乱arange(x). 但是shuffle会对x进行修改

In [59]:
arr2 = np.arange(8)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [63]:
np.random.shuffle(arr2)

In [64]:
arr2

array([5, 0, 7, 6, 1, 3, 4, 2])

### random.seed()

设置随机数种子

In [65]:
np.random.randint(1,8)

2

In [66]:
np.random.randint(1,8)

7

In [67]:
np.random.seed(100)

In [68]:
np.random.randint(1,8)

1

In [69]:
np.random.randint(1,8)

1