## NumPy-创建ndarray数组之创建指定形状的数组

- zeros()
- ones()
- empty()
- full()


In [1]:
import numpy as np

### np.zeros()   创建全零数组

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros((3,6,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

### np.ones()    生成全1的数组

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### np.empty()    创建未初始化的数组

np.empty() 函数只分配数组所使用的内存，不对数组元素进行初始化操作，因此它的运行速度是最快的。

In [21]:
np.empty(4)

array([2.71654920e-316, 0.00000000e+000, 8.29342548e-072, 5.45391360e-311])

In [22]:
np.empty((3, 3))

array([[2.71892151e-316, 2.14321575e-312, 2.37663529e-312],
       [2.56761491e-312, 1.10343781e-312, 6.95208261e-310],
       [6.95213259e-310, 6.95213259e-310, 3.95252517e-322]])

### np.full()创建元素初始化为指定值的数组

In [2]:
np.full(6, np.pi)

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265])

In [3]:
np.full(4, 8)

array([8, 8, 8, 8])

In [4]:
np.full((2,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [5]:
np.full(6, np.inf)

array([inf, inf, inf, inf, inf, inf])