# numpy-一通道图像变成三通道图像

## 方法一：

```python

np.array([mask for i in range(3)]).transpose(1,2,0)
```

其中mask的shape是(height,width).

如果是(height,width,1)那么应用第一种方法就需要删除维度

## 方法二：

np.repeat(mask[...,np.newaxis],3,2)

其中mask的shape是(height,width).

如果是(height,width,1)就需要去掉[...,np.newaxis]这一部分

In [2]:
import numpy as np
from PIL import Image

In [1]:
imgpath = "../../datas/images/xiaoren.png"

In [9]:
img = Image.open(imgpath)
img.show()

In [10]:
arr = np.array(img)
arr.shape

(600, 510)

## 方法一

In [11]:
arr1 = np.array([arr for i in range(3)]).transpose(1,2,0)
arr1.shape

(600, 510, 3)

In [12]:
img_new = Image.fromarray(arr1)
img_new.show()

## 方法二

In [13]:
arr.shape

(600, 510)

In [14]:
arr2 = np.repeat(arr[..., np.newaxis],3,2)
arr2.shape

(600, 510, 3)

In [15]:
img_new = Image.fromarray(arr2)
img_new.show()

## others

In [18]:
arr3 = np.arange(0,12).reshape(3,4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
arr4 = arr3[..., np.newaxis]
arr4

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [23]:
arr4.shape

(3, 4, 1)

In [26]:
np.repeat(arr4,3,2)

array([[[ 0,  0,  0],
        [ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3]],

       [[ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7]],

       [[ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10],
        [11, 11, 11]]])

In [27]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
arr5 = arr3[np.newaxis,...]
arr5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [31]:
arr5.shape

(1, 3, 4)