## NumPy-创建ndarray数组之from系列

- fromstring()
- frombuffer()
- fromfile()
- fromfunction()

In [1]:
import numpy as np

### fromstring()

```fromstring(string, dtype=float, count=-1, sep='')```

从字节序列创建数组

In [16]:
str = "abcdefgh"
np.fromstring(str,dtype=np.int8)    # ASCII编码

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


array([ 97,  98,  99, 100, 101, 102, 103, 104], dtype=int8)

In [17]:
np.fromstring(str,dtype=np.int16)    # 97 + 98 * 256 = 25185

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([25185, 25699, 26213, 26727], dtype=int16)

In [21]:
np.fromstring(str, dtype=np.int32)    25185+25699*256*256 = 1,684,234,849

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([1684234849, 1751606885])

In [11]:
str = "1 2"
np.fromstring(str, dtype=np.int, sep=" ")

array([1, 2])

In [13]:
str = "1 2 3"
np.fromstring(str, sep=" ")

array([1., 2., 3.])

In [14]:
str = "1,2,3"
np.fromstring(str, dtype=np.int, sep=",")

array([1, 2, 3])

- String_类型

In [63]:
str = "ancdefgh"

In [69]:
np.fromstring(str, dtype="S1")

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([b'a', b'n', b'c', b'd', b'e', b'f', b'g', b'h'], dtype='|S1')

In [73]:
np.fromstring(str, dtype="S2")

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([b'an', b'cd', b'ef', b'gh'], dtype='|S2')

### frombuffer()

```frombuffer(buffer, dtype=None, count=-1, offset=0)```

#frombuffer将data以流的形式读入转化成ndarray对象
#第一参数为stream,第二参数为返回值的数据类型，第三参数指定从stream的第几位开始读入
#data是字符串的时候，Python3默认str是Unicode类型，所以要转成bytestring在原str前加上b

In [24]:
str = b"abcdefgh"

In [25]:
np.frombuffer(str)

array([8.54088322e+194])

In [26]:
np.frombuffer(str, dtype=np.int16)

array([25185, 25699, 26213, 26727], dtype=int16)

In [29]:
np.frombuffer(str, dtype=np.int8)

array([ 97,  98,  99, 100, 101, 102, 103, 104], dtype=int8)

In [31]:
np.frombuffer(str, dtype=np.int8, offset=2)

array([ 99, 100, 101, 102, 103, 104], dtype=int8)

- String_ 类型

In [60]:
str = b"YouYongEducation"
np.frombuffer(str,dtype="S1")

array([b'Y', b'o', b'u', b'Y', b'o', b'n', b'g', b'E', b'd', b'u', b'c',
       b'a', b't', b'i', b'o', b'n'], dtype='|S1')

In [62]:
np.frombuffer(str,dtype="S2")

array([b'Yo', b'uY', b'on', b'gE', b'du', b'ca', b'ti', b'on'],
      dtype='|S2')

### np.fromstring()与np.frombuffer()的内存区别

- np.fromstring() 会对字符串的字节序列进行复制。

In [32]:
str = b"abcdefgh"

In [33]:
str1 = np.fromstring(str, dtype=np.int8)
str1

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([ 97,  98,  99, 100, 101, 102, 103, 104], dtype=int8)

In [47]:
str1[2] = 127    # int8: -128--127
str1

array([ 97,  98, 127, 100, 101, 102, 103, 104], dtype=int8)

- np.frombuffer() 创建的数组与原始字符串共享内存。

由于字符串萣只读的，因此无法修改所创建的数组的内容。

In [48]:
str2 = np.frombuffer(str, dtype=np.int8)
str2

array([ 97,  98,  99, 100, 101, 102, 103, 104], dtype=int8)

In [49]:
str2[2]=127

ValueError: assignment destination is read-only

### fromfile()

```fromfile(file, dtype=None, count=-1, sep='', offset=0)```

 file : file or str or Path
     Open file object or filename.
 - 具体参加NumPy-文件操作

### fromfunction()
```fromfunction(function, shape, **kwargs)```

fromfunction()的第一个参数是计算每个数组元素的函数，第二个参数指定数组的形状。

因为它支持多维数组，所以第二个参数必须是一个序列。

In [89]:
def func(x):
    return x / 2
np.fromfunction(func,(10,))

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [90]:
def func2(i,j):
    return (i + 1) * (j + 1)
np.fromfunction(func2,(9,9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

In [94]:
np.fromfunction(lambda i,j:(i+1)*(j+1),(9,9),dtype=np.int)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [92]:
np.fromfunction(lambda x,y:x==y, (4,6))

array([[ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False, False]])