## NumPy-文件操作

- tofile()
- fromfile()


- savetxt()
- loadtxt()


- save()
- savez()
- load()


- open()  文件对象

In [1]:
import numpy as np

### tofile() 存储

```arr.tofile(self, fid, sep="", format="%s")```
       
- 将数组中的数据以二进制格式写进文件

In [6]:
arr = np.arange(50).reshape(5,2,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [7]:
arr.tofile("arr50.csv", sep = ",", format = "%d")

In [8]:
arr.tofile("arr50.bat", sep = ",", format = "%.2f")

### np.fromfile() 读取

```fromfile(file, dtype=None, count=-1, sep='', offset=0)```

- `sep` : 数据分割字符串，如果是空串，写入文件为二进制。

In [9]:
arr_r = np.fromfile("arr50.csv", sep = ",")
arr_r

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [10]:
arr_r = np.fromfile("arr50.bat", sep = ",")
arr_r

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [11]:
arr_r = np.fromfile("arr50.csv", sep = ",", dtype=np.int)
arr_r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
arr_r = np.fromfile("arr50.csv", sep = ",", dtype=np.int).reshape(5,5,2)
arr_r

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

### np.savetxt() 存储

```savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='',footer='', comments='# ', encoding=None)```

- `frame` : 文件、字符串或产生器，可以是.gz或.bz2的压缩文件
- `X` : 存入文件的数组
- `fmt` : 写入文件的格式，例如：%d %.2f %.18e
- `delimiter` : 分割字符串，默认是任何空格

In [15]:
arr = np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [16]:
np.savetxt("arr100.csv", arr, fmt="%d")

In [17]:
np.savetxt("arr100comma.csv", arr, fmt="%d", delimiter=",")

### np.loadtxt()    读取

```loadtxt(fname, dtype=float, comments='#', delimiter=None,
            converters=None, skiprows=0, usecols=None, unpack=False,
            ndmin=0, encoding='bytes', max_rows=None)```

- `unpack` :If True, the returned array is transposed(转置)。

In [19]:
arr_r = np.loadtxt("arr100comma.csv", dtype = np.int, delimiter=",")
arr_r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
arr_r = np.loadtxt("arr100comma.csv", dtype = np.int, delimiter=",", unpack=True)
arr_r

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

### np.save()    存储

```save(file, arr, allow_pickle=True, fix_imports=True)```

In [21]:
arr = np.arange(80).reshape(10,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55]],

       [[56, 57, 58, 59],
        [60, 61, 62, 63]],

       [[64, 65, 66, 67],
        [68, 69, 70, 71]],

       [[72, 73, 74, 75],
        [76, 77, 78, 79]]])

In [25]:
np.save("arr80",arr)

In [26]:
np.save("arr80.npy",arr)

### np.load()    加载

```load(file, mmap_mode=None, allow_pickle=False, fix_imports=True,
         encoding='ASCII')```
     

In [27]:
arr_b = np.load("arr80.npy")
arr_b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55]],

       [[56, 57, 58, 59],
        [60, 61, 62, 63]],

       [[64, 65, 66, 67],
        [68, 69, 70, 71]],

       [[72, 73, 74, 75],
        [76, 77, 78, 79]]])

### np.savez()

```savez(file, *args, **kwds) ```

In [32]:
arr1 = np.ones((3,2))
arr1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
arr0 = np.zeros((4,4,2))
arr0

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [34]:
arr2 = np.full((5,5),2)
arr2

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [40]:
np.savez("arrz",arr0,arr1,arr2 = arr2)

In [41]:
arr_dic = np.load("arrz.npz")
arr_dic

In [42]:
arr_dic["arr_0"]

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [44]:
arr_dic["arr2"]

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [46]:
arr_dic["arr_1"]

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### file   文件对象

In [47]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [49]:
y = x + 10
y

array([10, 11, 12, 13])

In [50]:
z = x * y
z

array([ 0, 11, 24, 39])

In [54]:
f = open("out.npy","wb")
np.save(f, x)
np.save(f, y)
np.save(f, z)
f.close()

In [56]:
f = open("out.npy","rb")

In [57]:
np.load(f)

array([0, 1, 2, 3])

In [58]:
np.load(f)

array([10, 11, 12, 13])

In [59]:
np.load(f)

array([ 0, 11, 24, 39])

In [60]:
np.load(f)

ValueError: Cannot load file containing pickled data when allow_pickle=False

In [61]:
f.close()