## NumPy-创建ndarray数组之like系列

- zeros_like()
- ones_like()
- empty_like()
- full_like()


In [1]:
import numpy as np

### np.zeros_like()   根据已有数组结构创建全零数组

In [15]:
a = [[1,2,3],
     [4,5,6]]
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

### np.ones_like()   根据已有数组结构创建全1数组

In [20]:
np.ones_like(((1,2,3,4),
              (2,1,3,4)))

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### np.empty_like()   根据已有数组结构创建未初始化的数组

In [23]:
np.empty_like([[1,1,1],
               [2,2,2]])

array([[55536592,        0,        0],
       [       0,        0,        0]])

### np.full_like() 根据已有数组结构创建指定值的数组

In [3]:
a = np.empty((2,3))
np.full_like(a, 5)

array([[5., 5., 5.],
       [5., 5., 5.]])