## NumPy-创建ndarray数组之创建等差等比数组

- arange()
- linespace()
- logspace()


In [1]:
import numpy as np

### arange()函数
```arange([start,] stop[, step,], dtype=None)```

arange()类似于内置函数range()，通过指定开始值、终值和步长来创建表示等差数列的一维数组，注意所得到的结果中不包含终值。

- 创建起始值为1，终值为10，步长为1的等差数组

In [2]:
a = np.arange(1, 10, 1)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- 使用默认初始化值与步长进行创建终值为5的等差数组

In [5]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

- 使用默认初始化值创建终值为5、步长为2等差数组

In [6]:
a = np.arange(5, step=2)
a

array([0, 2, 4])

### linespace()函数

```linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,axis=0)```

linspace()通过指定幵始值、终值和元素个数来创建表示等差数列的一维数组，可以通过 endpoint参数指定是否包含终值，默认值为True,即包含终值。

In [21]:
a = np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
a = np.linspace(1,10,10,endpoint=False)
a

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [33]:
a = np.linspace(1,10,10, retstep=True)
a

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

### logspace()函数
```logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None,axis=0)```

logspace()所创建的数组是等比数列,和linspace()类似。

- 创建从$10^0$ 到$10^4$,有5个元素的等比数列，注意起始值0表示$10^0$,终值4表示$10^4$:

In [34]:
np.logspace(0,4,5)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04])

- 通过参数base制定基数

创建从$2^0$ 到$2^4$,有5个元素的等比数列:

In [35]:
np.logspace(0, 4, 5, base=2)

array([ 1.,  2.,  4.,  8., 16.])