## NumPy-创建ndarray数组之array函数
- array()

In [1]:
import numpy as np

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

### np.array()

可以通过给np.array()函数传递Python的序列对象来创建数组，如果传递的是多层嵌套的序列，将创建多维数组。

#### 使用一维列表创建

In [5]:
list1 = [1, 3, 5, 7, 9]
np.array(list1)

array([1, 3, 5, 7, 9])

#### 使用二维列表创建

In [6]:
list2 = [
    [1, 3, 5, 7, 9],
    [2, 4, 6, 8, 0]
]
np.array(list2)

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0]])

#### 使用一维元组创建

In [7]:
tup1 = (1, 2, 3, 4, 5)
np.array(tup1)

array([1, 2, 3, 4, 5])

#### 使用一维元组创建

In [9]:
tup2 = (
        (1, 3 ,5, 7, 9),
        (2, 4, 6, 8, 10))
np.array(tup2)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])