# NumPy-创建ndarray多维数组对象的几个常用函数
- array函数
- zeros函数
- ones函数
- empty函数

In [1]:
import numpy as np

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

# np.array()

## 使用一维列表创建

In [5]:
list1 = [1, 3, 5, 7, 9]
np.array(list1)

array([1, 3, 5, 7, 9])

## 使用二维列表创建

In [6]:
list2 = [
    [1, 3, 5, 7, 9],
    [2, 4, 6, 8, 0]
]
np.array(list2)

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0]])

## 使用一维元组创建

In [7]:
tup1 = (1, 2, 3, 4, 5)
np.array(tup1)

array([1, 2, 3, 4, 5])

## 使用一维元组创建

In [9]:
tup2 = (
        (1, 3 ,5, 7, 9),
        (2, 4, 6, 8, 10))
np.array(tup2)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

# np.zeros()   创建全零数组

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros((3,6,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

# np.zeros_like()   根据已有数组结构创建全零数组

In [15]:
a = [[1,2,3],
     [4,5,6]]
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

# np.ones()    生成全1的数组

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# np.ones_like()   根据已有数组结构创建全1数组

In [20]:
np.ones_like(((1,2,3,4),
              (2,1,3,4)))

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

# np.empty()    创建未初始化的数组

In [21]:
np.empty(4)

array([2.71654920e-316, 0.00000000e+000, 8.29342548e-072, 5.45391360e-311])

In [22]:
np.empty((3, 3))

array([[2.71892151e-316, 2.14321575e-312, 2.37663529e-312],
       [2.56761491e-312, 1.10343781e-312, 6.95208261e-310],
       [6.95213259e-310, 6.95213259e-310, 3.95252517e-322]])

# np.zeros_empty()   根据已有数组结构创建未初始化的数组

In [23]:
np.empty_like([[1,1,1],
               [2,2,2]])

array([[55536592,        0,        0],
       [       0,        0,        0]])

# ndarray其它创建方式
- arange函数
- linspace函数
- logspace函数
- 